const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),ts=require('typescript');
function load(file,requires,extra={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:k=>requires[k],Request,Response,fetch,process:{env:{SUPABASE_SERVICE_ROLE_KEY:'test-only'}},...extra});return exports}
const hr={id:'11111111-1111-4111-8111-111111111111',role:'hr',status:'approved',company_name:'The Workation',name:'HR',email:'hr@example.invalid'};
const emp={id:'22222222-2222-4222-8222-222222222222',role:'emp',status:'pending',company_name:'The Workation',name:'직원',email:'emp@example.invalid'};
function fixture(actor=hr,target=emp){let writes=0;const rows=[{...actor},{...target}];const db={auth:{getUser:async token=>({data:{user:token==='valid'?{id:actor.id}:null},error:token==='valid'?null:{}})},from(){const filters=[];let update;const q={select(){return q},eq(k,v){filters.push(r=>r[k]===v);return q},in(k,v){filters.push(r=>v.includes(r[k]));return q},order(){return q},update(v){update=v;return q},maybeSingle:async()=>{const found=rows.find(r=>filters.every(f=>f(r)));if(found&&update){Object.assign(found,update);writes++}return {data:found||null,error:null}},then(resolve){resolve({data:rows.filter(r=>filters.every(f=>f(r))),error:null})}};return q}};const helper=load('lib/server-membership.ts',{'@supabase/supabase-js':{createClient:()=>db}});const route=load('app/api/hr/members/route.ts',{'@/lib/server-membership':helper,'next/server':{NextResponse:{json:(body,init)=>Response.json(body,init)}}});return{route,writes:()=>writes,rows}}
const req=(token='valid',id=emp.id)=>new Request('https://example.invalid/api/hr/members',{method:'POST',headers:token?{Authorization:'Bearer '+token}:{},body:JSON.stringify({userId:id})});
test('anonymous and invalid tokens cannot approve',async()=>{for(const token of ['', 'invalid']){const f=fixture();assert.equal((await f.route.POST(req(token))).status,401);assert.equal(f.writes(),0)}});
test('employee or pending HR cannot approve',async()=>{for(const actor of [{...hr,role:'emp'},{...hr,status:'pending'}]){const f=fixture(actor);assert.equal((await f.route.POST(req())).status,403);assert.equal(f.writes(),0)}});
test('other companies and HR targets cannot be approved',async()=>{for(const target of [{...emp,company_name:'Other'},{...emp,role:'hr'}]){const f=fixture(hr,target);assert.equal((await f.route.POST(req())).status,403);assert.equal(f.writes(),0)}});
test('same company approval persists once and repeat is idempotent',async()=>{const f=fixture();assert.equal((await f.route.POST(req())).status,200);assert.equal(f.rows[1].status,'approved');assert.equal((await f.route.POST(req())).status,200);assert.equal(f.writes(),1)});
test('list is scoped to employees in caller company',async()=>{const f=fixture(hr,{...emp,company_name:'Other'});const r=await f.route.GET(new Request('https://example.invalid',{headers:{Authorization:'Bearer valid'}}));assert.equal(r.status,200);assert.deepEqual((await r.json()).members,[])});
test('invalid employee ID is rejected',async()=>{const f=fixture();assert.equal((await f.route.POST(req('valid','bad'))).status,400);assert.equal(f.writes(),0)});
