"use client"
import {useCallback,useEffect,useState} from 'react'
import Link from 'next/link'
import Header from '@/components/ui/Header'
import {memberRequest} from '@/lib/membership-client'
import type {Membership} from '@/lib/server-membership'
export default function MembersPage(){
 const [members,setMembers]=useState<Membership[]>([]),[company,setCompany]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState('pending'),[search,setSearch]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await memberRequest('/api/hr/members');setMembers(r.members);setCompany(r.company)}catch(e){setMembers([]);setCompany('');setError((e as Error).message)}finally{setLoading(false)}},[])
 useEffect(()=>{void load()},[load])
 async function approve(m:Membership){setBusy(m.id);setError('');setNotice('');try{await memberRequest('/api/hr/members',{method:'POST',body:JSON.stringify({userId:m.id})});setMembers(prev=>prev.map(v=>v.id===m.id?{...v,status:'approved'}:v));setNotice(`${m.name||m.email}님의 가입을 승인했습니다.`)}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 const visible=members.filter(m=>(filter==='all'||m.status===filter)&&`${m.name||''} ${m.email||''}`.toLowerCase().includes(search.toLowerCase()))
 return <div className="min-h-screen bg-slate-50 text-slate-900"><Header/><main className="max-w-4xl mx-auto px-5 py-8"><Link href="/dashboard" className="text-sm text-slate-500">← 인사담당자 대시보드</Link><div className="flex justify-between gap-3 mt-5 mb-6"><div><h1 className="text-2xl font-bold">직원 가입 승인</h1><p className="text-sm text-slate-600 mt-2">{company?`${company} 소속 직원의 신청을 확인합니다.`:'승인된 인사담당자 계정으로 로그인해 주세요.'}</p></div><button onClick={load} disabled={loading||!!busy} className="border rounded-xl px-4 py-3 bg-white text-sm disabled:opacity-50">새로고침</button></div><div className="rounded-2xl bg-blue-50 border border-blue-100 p-5 text-sm mb-6"><p>직원 가입 → 소속 확인 후 승인 → 직원이 승인 상태 확인</p><p className="mt-2">직원은 가입할 때 회사 목록에서 <strong>{company||'승인된 소속 회사'}</strong>를 선택해야 합니다.</p></div>{error&&<div role="alert" className="rounded-xl bg-red-50 text-red-700 p-4 mb-4">{error}<p className="mt-2"><Link href="/pending" className="underline mr-4">내 승인 상태 확인</Link><Link href="/login" className="underline">로그인</Link></p></div>}<p role="status" className="text-emerald-700 text-sm mb-4">{notice}</p><section className="bg-white border rounded-2xl p-5"><div className="flex flex-col sm:flex-row gap-4 justify-between mb-5"><div className="flex gap-2 flex-wrap">{[['pending','승인 대기'],['approved','승인 완료'],['all','전체']].map(([v,label])=><button key={v} onClick={()=>setFilter(v)} aria-pressed={filter===v} className={`px-3 py-2 rounded-lg text-sm ${filter===v?'bg-blue-600 text-white':'bg-slate-100'}`}>{label} {members.filter(m=>v==='all'||m.status===v).length}</button>)}</div><input aria-label="직원 이름 또는 이메일 검색" placeholder="이름·이메일 검색" value={search} onChange={e=>setSearch(e.target.value)} className="border rounded-lg px-3 py-2 text-sm"/></div>{loading?<p className="py-10 text-center">신청 목록을 불러오는 중입니다…</p>:!visible.length?<p className="py-10 text-center text-slate-500">{error?'목록을 불러오지 못했습니다.':'해당하는 직원 신청이 없습니다.'}</p>:<ul className="divide-y">{visible.map(m=><li key={m.id} className="py-4 flex items-center justify-between gap-4"><div className="min-w-0"><p className="font-semibold">{m.name||'이름 미입력'}</p><p className="text-sm text-slate-600 break-all">{m.email}</p><p className="text-xs text-slate-500 mt-1">{m.company_name}</p></div>{m.status==='pending'?<button onClick={()=>approve(m)} disabled={!!busy} aria-label={`${m.name||m.email} 가입 승인`} className="shrink-0 bg-blue-600 text-white rounded-xl px-4 py-3 text-sm font-semibold disabled:opacity-50">{busy===m.id?'승인 중…':'가입 승인'}</button>:<span className="text-sm text-emerald-700">승인 완료</span>}</li>)}</ul>}</section></main></div>
}
