import type { Goal } from '@/lib/workation-plan'
const field = 'mt-2 w-full rounded-xl border border-slate-300 px-3 py-3 focus:outline-none focus:ring-2 focus:ring-[#05828d] bg-white text-slate-900'
function TimeInput({ label, minutes, onChange }: { label: string; minutes: number; onChange: (n: number) => void }) {
  return <fieldset><legend className="font-medium text-sm">{label}</legend><div className="flex gap-3 mt-2"><label className="flex items-center gap-2"><input aria-label={`${label} 시간`} type="number" min="0" max="1666" className="w-24 border rounded-lg p-2" value={Math.floor(minutes / 60)} onChange={e => onChange(Number(e.target.value) * 60 + minutes % 60)} />시간</label><label className="flex items-center gap-2"><select aria-label={`${label} 분`} className="border rounded-lg p-2" value={minutes % 60} onChange={e => onChange(Math.floor(minutes / 60) * 60 + Number(e.target.value))}>{Array.from(new Set([0, 15, 30, 45, minutes % 60])).sort((a,b) => a-b).map(n => <option key={n} value={n}>{n}</option>)}</select>분</label></div></fieldset>
}
export default function WorkationGoalInput({ goal, editing, results = false, personal = false, start, end, change }: { goal: Goal; editing: boolean; results?: boolean; personal?: boolean; start: string; end: string; change: (key: keyof Goal, value: string | number) => void }) {
  return <div className="space-y-5 mt-4">
    {editing ? <><label className="block text-sm font-medium">어떤 일을 할 예정인가요? <span className="text-slate-400 font-normal">필수</span><input aria-label="수행할 업무" className={field} maxLength={200} value={goal.title} onChange={e => change('title', e.target.value)} placeholder="예: 서비스 소개 페이지 초안 만들기" /></label><label className="block text-sm font-medium">어디까지 하면 완료인가요? <span className="text-slate-400 font-normal">필수</span><p className="text-slate-500 font-normal mt-1">{personal ? '나중에 스스로 완료 여부를 확인할 기준을 적어 주세요.' : '담당자가 결과를 보고 확인할 수 있는 기준을 적어 주세요.'}</p><textarea aria-label="완료 기준" className={field} rows={3} maxLength={2000} value={goal.criteria} onChange={e => change('criteria', e.target.value)} placeholder="예: PC·모바일 화면을 모두 만들고 검토 링크 전달" /></label><div className="grid sm:grid-cols-2 gap-5"><label className="text-sm font-medium">언제까지 완료할까요?<input aria-label="목표 기한" className={field} type="date" min={start} max={end} value={goal.due} onChange={e => change('due', e.target.value)} /></label><TimeInput label="예상 소요 시간" minutes={goal.expectedMinutes} onChange={n => change('expectedMinutes', n)} /></div></> : <>
      {!results && <>{!personal && <fieldset><legend className="font-medium text-sm">진행 상태</legend><div className="flex flex-wrap gap-2 mt-2">{[[0,'시작 전'],[25,'시작했어요'],[50,'절반 정도'],[75,'마무리 중'],[100,'완료했어요']].map(([value,label]) => <button type="button" key={value} aria-pressed={goal.progress === value} onClick={() => change('progress', Number(value))} className={`rounded-full border px-3 py-2 text-sm ${goal.progress === value ? 'bg-[#056f7c] text-white border-[#056f7c]' : 'bg-white border-slate-200'}`}>{label}</button>)}</div><p className="text-xs text-slate-500 mt-2">{personal ? '내 기록' : '직원 기록'} {goal.progress}%</p></fieldset>}
      {!personal && <TimeInput label="지금까지 쓴 시간" minutes={goal.actualMinutes} onChange={n => change('actualMinutes', n)} />}
      <label className="block text-sm font-medium">진행 메모 <span className="text-slate-400 font-normal">선택</span><p className="font-normal text-slate-500 mt-1">달라진 점이나 도움이 필요한 내용만 남겨 주세요.</p><textarea aria-label="업무 기록" className={field} rows={3} maxLength={4000} value={goal.note} onChange={e => change('note', e.target.value)} placeholder={'예: 고객 인터뷰 3건 정리\n소개 페이지 문구와 화면 초안 작성'} /></label>
      </>}
      {results && <><label className="block text-sm font-medium">어떤 결과가 나왔나요? <span className="text-slate-400 font-normal">{personal ? '문서 정리 시 필수' : '결과 제출 시 필수'}</span><p className="font-normal text-slate-500 mt-1">완성한 것과 남은 일이 있다면 함께 적어 주세요.</p><textarea aria-label="최종 결과·미완료 사유" className={field} rows={3} maxLength={4000} value={goal.result} onChange={e => change('result', e.target.value)} placeholder="예: PC·모바일 초안 완성. 고객 의견 반영은 다음 주에 진행할 예정입니다." /></label><label className="block text-sm font-medium">결과물을 볼 수 있는 링크가 있나요? <span className="text-slate-400 font-normal">선택</span><input aria-label="결과물 링크 (선택)" className={field} type="url" value={goal.link} onChange={e => change('link', e.target.value)} placeholder="노션, 구글 문서, 디자인 또는 시연 페이지 주소" /></label>
      </>}
    </>}
  </div>
}
